name: All

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cocotb-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Python 3.9"
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        sudo apt-get install make gcc g++ python3.9-dev python3-pip ghdl-llvm iverilog
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Run make
      run: |
        pipenv run make
